CREATE DATABASE IF NOT EXISTS feedback_db;
USE feedback_db;
CREATE TABLE IF NOT EXISTS feedbacks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  rating INT NOT NULL,
  message TEXT NOT NULL,
  category VARCHAR(100) DEFAULT 'General',
  createdAt DATETIME NOT NULL,
  status VARCHAR(50) DEFAULT 'new'
) ENGINE=InnoDB CHARSET=utf8mb4;
SHOW TABLES;
SELECT DATABASE();