services:
  - type: web
    name: hearme-feedback-server
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_6bxqQirj8eGS@ep-jolly-mode-anxb2zoq-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: PORT
        value: 10000
    plan: free
